# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-09 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0082_remove_profile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'permissions': (('see_private_contest', 'See private contests'), ('edit_own_contest', 'Edit own contests'), ('edit_all_contest', 'Edit all contests'), ('contest_rating', 'Rate contests'), ('contest_access_code', 'Contest access codes'), ('contest_frozen_state', 'Change contest frozen state')), 'verbose_name': 'contest', 'verbose_name_plural': 'contests'},
        ),
        migrations.AddField(
            model_name='contest',
            name='first_submission_bonus',
            field=models.IntegerField(default=0, help_text='Bonus points for fully solving on first submission.', verbose_name=b'first try bonus'),
        ),
        migrations.AddField(
            model_name='contest',
            name='freeze_submissions',
            field=models.BooleanField(default=False, help_text='Whether submission updates should be frozen. If frozen, rejudging/rescoring will not propagate to related contest submissions until after this is unchecked.', verbose_name=b'freeze submissions'),
        ),
        migrations.AddField(
            model_name='contest',
            name='time_bonus',
            field=models.IntegerField(default=0, help_text='Number of minutes to award an extra point for submitting before the contest end. Leave as 0 for no time bonus.', verbose_name=b'time bonus'),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='bonus',
            field=models.IntegerField(default=0, verbose_name='bonus'),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='updated_frozen',
            field=models.BooleanField(default=False, help_text='Whether this submission was rejudged/rescored while the contest was frozen.', verbose_name='updated while frozen'),
        ),
    ]
